### ISSUE TITLE
Outdated version of kubectl

### ISSUE THREAD

**Issue by nielskrijger** [ployst/docker-letsencrypt#16]
Running the `save_certs.sh` script on a k8s kluster on v1.6.1 generated the following error after generating a DH param:

```
error: group map[apps:0xc820374b60 batch:0xc820374cb0 authentication.k8s.io:0xc820374f50 certificates.k8s.io:0xc8202d6620 federation:0xc820374a80 authorization.k8s.io:0xc820374bd0 autoscaling:0xc820374c40 componentconfig:0xc820374d20 extensions:0xc820374d90 policy:0xc820374e00 rbac.authorization.k8s.io:0xc820374e70 :0xc820374af0] is already registered
error: group map[authentication.k8s.io:0xc820376f50 federation:0xc820376a80 :0xc820376af0 autoscaling:0xc820376c40 batch:0xc820376cb0 componentconfig:0xc820376d20 policy:0xc820376e00 apps:0xc820376b60 authorization.k8s.io:0xc820376bd0 extensions:0xc820376d90 rbac.authorization.k8s.io:0xc820376e70] is already registered
```

Updating the version number of the kubectl install fixed the issue.

Someone already forked this repo and updated the version number:
https://github.com/z1nkum/docker-letsencrypt

The changes of that fork can be found here:
https://github.com/z1nkum/docker-letsencrypt/commit/f9446b6d088ba7f29545eda97a5b5bc2d3b9fdc9

Not sure about the best approach here how to release/version number such an update. Just wanted to let you and others know this issue exists.

**Comment by alexcouper** [comment]
Released as 0.3.0
